command-ad = 🎁 Get reward
command-ban = 🔨 Ban user
command-donate = 🛒 Donate
command-cancel = ❌ Universal cancel
command-chat_id = 📱 Get chat ID
command-chat_settings = ⚙️ Chat settings
command-commands = 📜 Commands
command-help = 💁‍♂️ Help
command-inventory = ✨ Inventory
command-kick = 🔥 Kick user
command-language = 🌐 Change language
command-mute = 🔇 Mute user
command-pardon = 🔓 Pardon user
command-pay = 💸 Transfer items
command-phantom = 👻 Enable phantom mode
command-support = 🆘 Support
command-profile = 👤 Profile
command-r = 🔄 Refresh
command-reload = 🔄 Reload chat settings
command-report = 📢 Report
command-settings = ⚙️ Settings
command-shop = 🏪 Shop
command-sr = 💬 Change Ban/Mute reason
command-start = ⭐️ Start
command-tokenize = 📦 Tokenize
command-tokenlist = 🗒 Token list
command-trade = 🔄 Trade
command-ui = ✨ Weapon inventory
command-unpack = ↖️ Unpack token
command-refund = 💰 Refund Telegram Stars
command-terms = 📔 Terms of use
command-privacy = 📜 Privacy policy
