# keyboards--goto_start-button = 🏠 На головну
keyboards--main-button = 📜 General
keyboards--admin-button = 👮‍♂️ Admin
keyboards--vip-button = 👑 VIP 
keyboards--other-button = 🔮 Other
keyboards--profile-button = 👤 Profile
keyboards--language-button = 🌐 Language | Мова
keyboards--commands-button = 📚 Commands
keyboards--add_to_group-button = 🚀 Add Bot to Group
keyboards--inventory-button = 📦 Inventory
# keyboards--more_info-button = 📖 Більше інформації
keyboards--settings-button = ⚙️ Settings
keyboards--close-button = ❌ Close
