# keyboards--en-button = 🇺🇸 English
# keyboards--uk-button = 🇺🇦 Українська
# keyboards--ru-button = 🇷🇺 Российский
keyboards--goto_start-button = 🏠 Go to start
keyboards--main-button = 📜 General
keyboards--admin-button = 👮‍♂️ Admin
keyboards--vip-button = 👑 VIP 
keyboards--other-button = 🔮 Other
keyboards--profile-button = 👤 Profile
keyboards--language-button = 🌐 Language | Мова
keyboards--commands-button = 📚 Commands
keyboards--add_to_group-button = 🚀 Add Bot to Group
keyboards--inventory-button = 📦 Inventory
keyboards--more_info-button = 📖 More information
