language--language = language
language--lang = lang
language--choose_lang = 🌐 Choose language
language--select_callback-success = Selected language: { $language }
language--en = 🇺🇸 English
language--uk = 🇺🇦 Українська
language--ru = 🇷🇺 Российский
language--pl = 🇵🇱 Polski
language--de = 🇩🇪 Deutsch
language--ja = 🇯🇵 日本語
