language--language = language
language--lang = lang
language--choose_lang = 🌐 Choose language
language--select_callback-success = Selected language: { $language }
language--en = language--en
language--uk = language--uk
language--ru = language--ru
language--pl = language--pl
language--de = language--de
language--ja = language--ja
