pay-reply_required = pay-reply_required
pay-sender_chat-not_supported = pay-sender_chat-not_supported
pay-bot-not_supported = pay-bot-not_supported
pay-cant_pay_self = pay-cant_pay_self
pay-specify_items = pay-specify_items
pay-accept_button = pay-accept_button
pay-decline_button = pay-decline_button
pay-transfer_declined = pay-transfer_declined
pay-deprecated = pay-deprecated
pay-not_enough_item = pay-not_enough_item{ $item_emoji }{ $item_name }{ $item_amount }
pay-transfer_accepted = pay-transfer_accepted{ $receiver_mention }{ $receiver_gender }{ $items }
trade-separator_literal = trade-separator_literal
trade-specify_items = trade-specify_items
trade-no_separator_found = trade-no_separator_found
trade-accept_button = trade-accept_button
trade-decline_button = trade-decline_button
trade-same_items = trade-same_items
trade-deprecated = trade-deprecated
trade-not_enough_item = trade-not_enough_item{ $user_mention }{ $item_emoji }{ $item_name }{ $item_amount }
trade-success = trade-success{ $sender_mention }{ $receiver_mention }{ $sender_gender }{ $receiver_gender }{ $sender_items }{ $receiver_items }
trade-waiting_for_answer = trade-waiting_for_answer{ $sender_mention }{ $receiver_mention }{ $sender_gender }{ $receiver_gender }{ $sender_items }{ $receiver_items }{ $sender_accepted }{ $receiver_accepted }
trade-declined = trade-declined{ $sender_mention }{ $receiver_mention }{ $sender_gender }{ $receiver_gender }{ $sender_items }{ $receiver_items }{ $sender_accepted }{ $receiver_accepted }
trade-reply_required = trade-reply_required
trade-sender_chat-not_supported = trade-sender_chat-not_supported
trade-bot-not_supported = trade-bot-not_supported
trade-cant_trade_self = trade-cant_trade_self
pay-waiting_for_answer = pay-waiting_for_answer{ $sender_gender }{ $receiver_mention }{ $items }
trade-already_accepted = trade-already_accepted{ $gender }
pay-user_not_own_unique_item = pay-user_not_own_unique_item{ $uuid }
trade-user_not_own_unique_item = trade-user_not_own_unique_item{ $user_mention }{ $uuid }
tokenize-not_enough_item = tokenize-not_enough_item{ $item_emoji }{ $item_name }{ $item_amount }
tokenize-accept_button = tokenize-accept_button
tokenize-user_not_own_unique_item = tokenize-user_not_own_unique_item{ $uuid }
tokenize-decline_button = tokenize-decline_button
tokenize-deprecated = tokenize-deprecated
tokenize-specify_items = tokenize-specify_items
tokenize-declined = tokenize-declined
tokenize-tokenizations_success = tokenize-tokenizations_success{ $token_id }{ $items }
tokenize-waiting_for_answer = tokenize-waiting_for_answer{ $gender }{ $items }
unpack-token_not_found_or_used = unpack-token_not_found_or_used
unpack-success = unpack-success{ $items }
unpack-specify_token = unpack-specify_token
unpack-invalid_token = unpack-invalid_token
unpack-token_used_by = unpack-token_used_by{ $token_id }{ $user_mention }{ $items }
