report-reason-required = report-reason-required
report-reason-too-long = report-reason-too-long
report-bot-needs-admin-rights = reports-bot-needs-admin-rights
report-reply-required = reports-reply-required
reports-disabled-in_-chat = reports-disabled-in_-chat
failed-to-copy-report-message-to-special-chat = failed-to-copy-report-message-to-special-chat
special-chat-not_-set = special-chat-not_-set
report-message-text = report-message-text{ $reporter_id }{ $reporter_mention }{ $reported_id }{ $reported_mention }{ $violation_message }{ $reason }
special-report-message-text = special-report-message-text{ $chat_id }{ $chat_title }{ $reporter_id }{ $reporter_mention }{ $reported_id }{ $reported_mention }{ $violation_message }{ $reason }
report-cannot-report-selfbot = report-cannot-report-selfbot
