chat_settings--window-closed = chat_settings--window-closed
# chat_settings--main-settings = chat_settings--main-settings
chat_settings--admin-settings = chat_settings--admin-settings
chat_settings--game-settings = chat_settings--game-settings
chat_settings--language = chat_settings--language { $language_code }
chat_settings--timezone = chat_settings--timezone { $timezone }
# chat_settings--greetings-enabled = chat_settings--greetings-enabled { $enabled }
# # chat_settings--set-greetings = chat_settings--set-greetings
# # # chat_settings--farewell-enabled = chat_settings--farewell-enabled
# # chat_settings--set-farewell = chat_settings--set-farewell
# # # chat_settings--reports-enabled = chat_settings--reports-enabled
# # chat_settings--set-reports-policy = chat_settings--set-reports-policy { $policy }
# # chat_settings--reports-special-chat-id = chat_settings--reports-special-chat-id { $chat_id }
chat_settings--back = chat_settings--back
chat_settings--main-window-text = chat_settings--main-window-text
chat_settings--general-settings-window-text = chat_settings--general-settings-window-text
chat_settings--general-settings = chat_settings--general-settings
chat_settings--not-set = chat_settings--not-set
# chat_settings--farewell-enableds = chat_settings--farewell-enableds { $enabled }
# chat_settings--farewell-enabled = chat_settings--farewell-enabled { $enabled }
# # chat_settings--reports-enableds = chat_settings--reports-enableds { $enabled }
chat_settings--reports-enabled = chat_settings--reports-enabled { $enabled }
# chat_settings--setup = chat_settings--setup { $enabled }
chat_settings--farewell-enabled = chat_settings--farewell-enabled { $enabled }
# chat_settings--setups = chat_settings--setups
chat_settings--setup = chat_settings--setup
# chat_settings--set-reports-policyz = chat_settings--set-reports-policyz
# chat_settings--set-reports-policy = chat_settings--set-reports-policy
# # chat_settings--language-code = chat_settings--language-code { $language_code }
# # chat_settings--select-language-window-text = chat_settings--select-language-window-text
chat_settings--language-code = chat_settings--language-code { $language_code }
chat_settings--exit = chat_settings--exit
chat_settings--set-language-window-text = chat_settings--set-language-window-text
# chat_settings--select-timezone-continent-text = chat_settings--select-timezone-continent-text
chat_settings--timezone-help-button = chat_settings--timezone-help-button
chat_settings--timezone-help-url = chat_settings--timezone-help-url
chat_settings--set-timezone-text = chat_settings--set-timezone-text
chat_settings--unknown-timezone = chat_settings--unknown-timezone
chat_settings--timezone-saved = chat_settings--timezone-saved { $timezone }
chat_settings--unknown-timezone-try-again = chat_settings--unknown-timezone-try-again
# chat_settings--set-greetings-text = chat_settings--set-greetings-text
# chat_settings--greetings-too-long = chat_settings--greetings-too-long
# chat_settings--greetings-too-long-try-again = chat_settings--greetings-too-long-try-again
# chat_settings--greetings-saved = chat_settings--greetings-saved
# chat_settings--set-greetings-texts = chat_settings--set-greetings-texts
# chat_settings--greetings-set-type = chat_settings--greetings-set-type { $greeting_type }
# chat_settings--greetings-set-text-button = chat_settings--greetings-set-text-button
chat_settings--reset-button = chat_settings--reset-button
# chat_settings--greetings-set-media-button = chat_settings--greetings-set-media-button
# chat_settings--greetings-set-topic-button = chat_settings--greetings-set-topic-button
chat_settings--reset-all-button = chat_settings--reset-all-button
# chat_settings--set-greetings-window-text = chat_settings--set-greetings-window-text
# # chat_settings--set-greetings-type-window-text = chat_settings--set-greetings-type-window-text
# chat_settings--greetings-set-type-text-button = chat_settings--greetings-set-type-text-button
# chat_settings--greetings-set-type-photo-button = chat_settings--greetings-set-type-photo-button
# chat_settings--greetings-set-type-video-button = chat_settings--greetings-set-type-video-button
# chat_settings--greetings-set-type-gif-button = chat_settings--greetings-set-type-gif-button
# chat_settings--greetings-set-type-sticker-button = chat_settings--greetings-set-type-sticker-button
# chat_settings--greetings-set-type-window-text = chat_settings--greetings-set-type-window-text
# # chat_settings--greetings-reset-text-success = chat_settings--greetings-reset-text-success
# # chat_settings--greetings-reset-media-id-success = chat_settings--greetings-reset-media-id-success
# # chat_settings--greetings-reset-topic-id-success = chat_settings--greetings-reset-topic-id-success
# # chat_settings--greetings-set-text-window-text = chat_settings--greetings-set-text-window-text
# chat_settings--greetings-set-text-too-long = chat_settings--greetings-set-text-too-long { $max_length }
# chat_settings--greetings-set-media-window-text = chat_settings--greetings-set-media-window-text
# # chat_settings--greetings-set-topic-id-window-text = chat_settings--greetings-set-topic-id-window-text
# chat_settings--greetings-set-text-window-text = chat_settings--greetings-set-text-window-text
# # chat_settings--greetings-set-topic-id-incorrect-topic-id = chat_settings--greetings-set-topic-id-incorrect-topic-id
# chat_settings--greetings-reset-topic-id-success = chat_settings--greetings-reset-topic-id-success
# chat_settings--greetings-set-topic-id-success = chat_settings--greetings-set-topic-id-success
# chat_settings--greetings-set-topic-id-chat-is-not-a-topic-type = chat_settings--greetings-set-topic-id-chat-is-not-a-topic-type
# # chat_settings--greetings-set-topic-id-window-texts = chat_settings--greetings-set-topic-id-window-texts { $stored_topic_id }
# chat_settings--greetings-set-topic-id-window-text = chat_settings--greetings-set-topic-id-window-text { $stored_topic_id }
chat_settings--set-topic-id-topic-closed = chat_settings--set-topic-id-topic-closed { $mention }
# chat_settings--reports-special-chat = chat_settings--reports-special-chat { $chat_id }
# chat_settings--reports-special-chat-text = chat_settings--reports-special-chat-text { $is_set } { $chat_id }
chat_settings--reports-policy-text = chat_settings--reports-policy-text
chat_settings--reports-policy = chat_settings--reports-policy
chat_settings--set-reports-special-chat = chat_settings--set-reports-special-chat
chat_settings--reports-special-chat-choose-chat = chat_settings--reports-special-chat-choose-chat
# chat_settings--reports-special-chat-texts = chat_settings--reports-special-chat-texts { $is_set } { $chat_id }
chat_settings--reports-special-chat-text = chat_settings--reports-special-chat-text { $is_set } { $chat_id }
chat_settings--no-pending-reports-special-chat-title = chat_settings--no-pending-reports-special-chat-title
chat_settings--no-pending-reports-special-chat-text = chat_settings--no-pending-reports-special-chat-text
chat_settings--set-reports-special-chat-inline-query-title = chat_settings--set-reports-special-chat-inline-query-title
chat_settings--set-reports-special-chat-success-text = chat_settings--set-reports-special-chat-success-text
chat_settings--set-reports-special-chat-default-text = chat_settings--set-reports-special-chat-default-text
chat_settings--admin-settings-window-text = chat_settings--admin-settings-window-text
chat_settings--greeting-enabled = chat_settings--greeting-enabled { $enabled }
chat_settings--farewell-set-media-window-text = chat_settings--farewell-set-media-window-text
chat_settings--farewell-set-text-window-text = chat_settings--farewell-set-text-window-text
# chat_settings--farewell-set-text-too-long = chat_settings--farewell-set-text-too-long { $max_length }
chat_settings--set-topic-id-chat-is-not-a-topic-type = chat_settings--set-topic-id-chat-is-not-a-topic-type
chat_settings--set-topic-id-window-text = chat_settings--set-topic-id-window-text { $stored_topic_id }
chat_settings--set-topic-id-success = chat_settings--set-topic-id-success { $topic_id }
chat_settings--reset-topic-id-success = chat_settings--reset-topic-id-success
chat_settings--farewell-set-type-window-text = chat_settings--farewell-set-type-window-text
chat_settings--farewell-set-type-text = chat_settings--farewell-set-type-text { $farewell_type }
chat_settings--set-type-text-button = chat_settings--set-type-text-button
chat_settings--set-media-button = chat_settings--set-media-button
chat_settings--set-topic-button = chat_settings--set-topic-button
chat_settings--set-type-photo-button = chat_settings--set-type-photo-button
chat_settings--set-type-video-button = chat_settings--set-type-video-button
chat_settings--set-type-gif-button = chat_settings--set-type-gif-button
chat_settings--set-type-sticker-button = chat_settings--set-type-sticker-button
chat_settings--set-farewell-window-text = chat_settings--set-farewell-window-text
# chat_settings--farewell-reset-topic-id-success = chat_settings--farewell-reset-topic-id-success
chat_settings--greeting-set-media-window-text = chat_settings--greeting-set-media-window-text
chat_settings--greeting-set-text-window-text = chat_settings--greeting-set-text-window-text
# chat_settings--greeting-set-text-too-long = chat_settings--greeting-set-text-too-long { $max_length }
chat_settings--greeting-set-type-window-text = chat_settings--greeting-set-type-window-text
chat_settings--greeting-set-type-text = chat_settings--greeting-set-type-text { $greeting_type }
chat_settings--set-greeting-window-text = chat_settings--set-greeting-window-text
chat_settings--window-deprecated = chat_settings--window-deprecated
chat_settings--set-text-too-long = chat_settings--set-text-too-long { $max_length }
