chat_settings--window-closed = chat_settings--window-closed
# chat_settings--main-settings = chat_settings--main-settings
chat_settings--admin-settings = chat_settings--admin-settings
chat_settings--game-settings = chat_settings--game-settings
chat_settings--language = chat_settings--language { $language_code }
chat_settings--timezone = chat_settings--timezone { $timezone }
chat_settings--greetings-enabled = chat_settings--greetings-enabled { $enabled }
# chat_settings--set-greetings = chat_settings--set-greetings
# # chat_settings--farewell-enabled = chat_settings--farewell-enabled
# chat_settings--set-farewell = chat_settings--set-farewell
# # chat_settings--reports-enabled = chat_settings--reports-enabled
# chat_settings--set-reports-policy = chat_settings--set-reports-policy { $policy }
chat_settings--reports-special-chat-id = chat_settings--reports-special-chat-id { $chat_id }
chat_settings--back = chat_settings--back
chat_settings--main-window-text = chat_settings--main-window-text
chat_settings--general-settings-window-text = chat_settings--general-settings-window-text
chat_settings--general-settings = chat_settings--general-settings
chat_settings--not-set = chat_settings--not-set
# chat_settings--farewell-enableds = chat_settings--farewell-enableds { $enabled }
# chat_settings--farewell-enabled = chat_settings--farewell-enabled { $enabled }
# # chat_settings--reports-enableds = chat_settings--reports-enableds { $enabled }
chat_settings--reports-enabled = chat_settings--reports-enabled { $enabled }
# chat_settings--setup = chat_settings--setup { $enabled }
chat_settings--farewell-enabled = chat_settings--farewell-enabled { $enabled }
# chat_settings--setups = chat_settings--setups
chat_settings--setup = chat_settings--setup
# chat_settings--set-reports-policyz = chat_settings--set-reports-policyz
chat_settings--set-reports-policy = chat_settings--set-reports-policy
# chat_settings--language-code = chat_settings--language-code { $language_code }
# chat_settings--select-language-window-text = chat_settings--select-language-window-text
chat_settings--language-code = chat_settings--language-code { $language_code }
chat_settings--exit = chat_settings--exit
chat_settings--set-language-window-text = chat_settings--set-language-window-text
# chat_settings--select-timezone-continent-text = chat_settings--select-timezone-continent-text
chat_settings--timezone-help-button = chat_settings--timezone-help-button
chat_settings--timezone-help-url = chat_settings--timezone-help-url
chat_settings--set-timezone-text = chat_settings--set-timezone-text
chat_settings--unknown-timezone = chat_settings--unknown-timezone
chat_settings--timezone-saved = chat_settings--timezone-saved { $timezone }
chat_settings--unknown-timezone-try-again = chat_settings--unknown-timezone-try-again
