restrictions-mute--set-user-or-reply = restrictions-mute--set-user-or-reply
restrictions-mute--usage = restrictions-mute--usage
restrictions-mute--cant-mute-admin = restrictions-mute--cant-mute-admin
restrictions-mute--cant-mute-self = restrictions-mute--cant-mute-self
restrictions-mute--error = restrictions-mute--error
restrictions-mute--text = restrictions-mute--text { $admin_mention } { $victim_mention } { $victim_id } { $until_date } { $reason }
# restrictions-mute--cant-mute-sender-chat = restrictions-mute--cant-mute-sender-chat
# # restrictions-mute--usage-advanced = restrictions-mute--usage-advanced
restrictions-mute--usage-advanced = restrictions-mute--usage-advanced
