restrictions-set_reason-not_restriction_message_or_expired = restrictions-set_reason-not_restriction_message_or_expired
restrictions-set_reason-mute_message = restrictions-set_reason-mute_message{ $victim_id }{ $victim_mention }{ $admin_mention }{ $until_date }{ $edited_by }{ $reason }
restrictions-set_reason-ban_message = restrictions-set_reason-ban_message{ $victim_id }{ $victim_mention }{ $admin_mention }{ $until_date }{ $edited_by }{ $reason }
restrictions-set_reason-kick_message = restrictions-set_reason-kick_message{ $victim_id }{ $victim_mention }{ $admin_mention }{ $edited_by }{ $reason }
restrictions-set_reason-pardon_message = restrictions-set_reason-pardon_message{ $victim_id }{ $victim_mention }{ $admin_mention }{ $edited_by }{ $reason }
restrictions-set_reason-ban_sc_message = restrictions-set_reason-ban_sc_message{ $victim_id }{ $victim_mention }{ $admin_mention }{ $edited_by }{ $reason }
restrictions-set_reason-pardon_sc_message = restrictions-set_reason-pardon_sc_message{ $victim_id }{ $victim_mention }{ $admin_mention }{ $edited_by }{ $reason }
restrictions-set_reason-unknown_restriction_type = restrictions-set_reason-unknown_restriction_type
restrictions-set_reason-usage = restrictions-set_reason-usage
restrictions-set_reason-usage-advanced = restrictions-set_reason-usage-advanced
