restrictions-set_reason--usage = restrictions-set_reason--usage
restrictions-set_reason--not_restriction_message_or_expired = restrictions-set_reason--not_restriction_message_or_expired
restrictions-set_reason--mute_message = restrictions-set_reason--mute_message { $admin_mention } { $edited_by } { $until_date } { $victim_id } { $reason } { $victim_mention }
restrictions-set_reason--ban_message = restrictions-set_reason--ban_message { $admin_mention } { $edited_by } { $until_date } { $victim_id } { $reason } { $victim_mention }
restrictions-set_reason--kick_message = restrictions-set_reason--kick_message { $admin_mention } { $edited_by } { $victim_id } { $reason } { $victim_mention }
restrictions-set_reason--pardon_message = restrictions-set_reason--pardon_message { $admin_mention } { $edited_by } { $victim_id } { $reason } { $victim_mention }
restrictions-set_reason--ban_sc_message = restrictions-set_reason--ban_sc_message { $reason } { $edited_by } { $admin_mention } { $victim_id } { $until_date } { $victim_mention }
restrictions-set_reason--pardon_sc_message = restrictions-set_reason--pardon_sc_message { $reason } { $edited_by } { $admin_mention } { $victim_id } { $victim_mention }
restrictions-set_reason--unknown_restriction_type = restrictions-set_reason--unknown_restriction_type
restrictions-set_reason--usage-advanced = restrictions-set_reason--usage-advanced
