victim-already-kus-ed = victim-already-kus-ed{ $victim }
predator_zero_kus_quantity = predator_zero_kus_quantity
predator-has-disarm-status = predator-has-disarm-status{ $predator }
victim-not-in-game = victim-not-in-game{ $victim }
admin-cant-be-kused = admin-cant-be-kused
admin-self-kus = admin-self-kus{ $predator }
member-self-kus = member-self-kus{ $predator }
admin-kus-protected-victim = admin-kus-protected-victim{ $victim }
admin-break-armor-and-kus-admin = admin-break-armor-and-kus-admin{ $predator }{ $victim }
admin-break-armor-and-kus-member = admin-break-armor-and-kus-member{ $predator }{ $victim }
admin-dont-break-armor-and-get-disarm = admin-dont-break-armor-and-get-disarm{ $predator }{ $victim }
admin-kus-admin = admin-kus-admin{ $predator }{ $victim }
admin-kus-member = admin-kus-member{ $predator }{ $victim }
member-break-armor-and-kus-admin = member-break-armor-and-kus-admin{ $predator }{ $victim }
member-break-armor-and-kus-member = member-break-armor-and-kus-member{ $predator }{ $victim }
member-dont-break-armor-and-get-restrict = member-dont-break-armor-and-get-restrict{ $predator }{ $victim }
member-kus-admin = member-kus-admin{ $predator }{ $victim }
member-kus-member = member-kus-member{ $predator }{ $victim }
