inventory = inventory
i = i
inventory-items = inventory-items
inventory-resources = inventory-resources
inventory-weapons = inventory-weapons
inventory-close = inventory-close
inventory-items-text = inventory-items-text{ $items }
inventory-closed = inventory-closed
inventory-unknown-window = inventory-unknown-window
inventory-resources-text = inventory-resources-text{ $resources }
inventory-weapons-text = inventory-weapons-text
inventory-no_weapons = inventory-no_weapons
inventory-weapons-deprecated = inventory-weapons-deprecated
inventory-weapons-detailed_button = inventory-weapons-detailed_button{ $weapon }
inventory-cancel-and_-back = inventory-cancel-and_-back
