language--language = мова
language--lang = мова
language--choose_lang = 🌐 Виберіть мову
language--select_callback-success = Обрано мову: { $language }
language--en = 🇺🇸 English
language--uk = 🇺🇦 Українська
language--ru = 🇷🇺 Российский
language--pl = 🇵🇱 Polski
language--de = 🇩🇪 Deutsch
language--ja = 🇯🇵 日本語
