restrictions-general--show-advanced-info = restrictions-general--show-advanced-info
# restrictions-general--set-user-or-reply = restrictions-general--set-user-or-reply
restrictions-general--close-advanced-info = restrictions-general--close-advanced-info
restrictions-general--closed = restrictions-general--closed
restrictions-general--not-enough-rights = restrictions-general--not-enough-rights
restrictions-general--reason-too-long = restrictions-general--reason-too-long { $max_length }
restrictions-general--no-reason = restrictions-general--no-reason
restrictions-general--forever = restrictions-general--forever
restrictions-general--cant-restrict-sender-chat = restrictions-general--cant-restrict-sender-chat
