settings-gender-male = settings-gender-male
settings-gender-female = settings-gender-female
settings-gender-text = settings-gender-text
settings-gender-selected-text = settings-gender-selected-text{ $gender }
settings-gender-button = settings-gender-button
settings-close-button = settings-close-button
settings-choose-language = settings-choose-language
settings-language = settings-language
settings-lang = settings-lang
settings-language-selected-text = settings-language-selected-text{ $language }
settings-language-code = settings-language-code{ $language_code }
settings-text = settings-text{ $language }{ $gender }
settings = settings
settings-closed = settings-closed
