item-kus-name = Кусь
item-kus-description = Укуси свою жертву и заставь еë молчать целую минуту!
item-armor-name = Щит
item-armor-description = С некоторым шансом защитит тебя от укуса.
item-kukus-name = Кукусь
item-kukus-description = Усиленная версия обычного Кусь. Даëт возможность укусить жертву и заставить еë молчать 5 минут!
item-kuscoin-name = КусьКоин
item-kuscoin-description = Валюта, которую можно потратить на покупку разных предметов.
item-vip-name = VIP
item-vip-description = item-vip-description
