chat_settings-no-pending-reports-special-chat-title = chat_settings-no-pending-reports-special-chat-title
chat_settings-no-pending-reports-special-chat-text = chat_settings-no-pending-reports-special-chat-text
chat_settings-set-reports-special-chat-inline-query-title = chat_settings-set-reports-special-chat-inline-query-title
chat_settings-window-closed = chat_settings-window-closed
chat_settings-set-reports-special-chat-success-text = chat_settings-set-reports-special-chat-success-text{ $chat_id }
chat_settings-set-reports-special-chat-default-text = chat_settings-set-reports-special-chat-default-text
chat_settings-general-settings = chat_settings-general-settings
chat_settings-admin-settings = chat_settings-admin-settings
chat_settings-game-settings = chat_settings-game-settings
chat_settings-exit = chat_settings-exit
chat_settings-main-window-text = chat_settings-main-window-text
chat_settings-reports-enabled = chat_settings-reports-enabled{ $enabled }
chat_settings-reports-policy = chat_settings-reports-policy
chat_settings-back = chat_settings-back
chat_settings-admin-settings-window-text = chat_settings-admin-settings-window-text
chat_settings-language-code = chat_settings-language-code{ $language_code }
chat_settings-timezone-help-button = chat_settings-timezone-help-button
chat_settings-language = chat_settings-language{ $language_code }
chat_settings-timezone = chat_settings-timezone{ $timezone }
chat_settings-greeting-enabled = chat_settings-greeting-enabled{ $enabled }
chat_settings-setup = chat_settings-setup
chat_settings-farewell-enabled = chat_settings-farewell-enabled{ $enabled }
chat_settings-general-settings-window-text = chat_settings-general-settings-window-text
chat_settings-set-language-window-text = chat_settings-set-language-window-text
chat_settings-set-timezone-text = chat_settings-set-timezone-text
chat_settings-unknown-timezone = chat_settings-unknown-timezone
chat_settings-unknown-timezone-try_-again = chat_settings-unknown-timezone-try_-again
chat_settings-timezone-saved = chat_settings-timezone-saved{ $timezone }
chat_settings-set-reports-special-chat = chat_settings-set-reports-special-chat
chat_settings-reports-special-chat-choose-chat = chat_settings-reports-special-chat-choose-chat
chat_settings-reports-policy-text = chat_settings-reports-policy-text{ $is_set }
chat_settings-reports-special-chat-text = chat_settings-reports-special-chat-text{ $is_set }{ $chat_id }
chat_settings-farewell-set-media-window-text = chat_settings-farewell-set-media-window-text
chat_settings-farewell-set-text-window-text = chat_settings-farewell-set-text-window-text
chat_settings-set-text-too-long = chat_settings-set-text-too-long{ $max_length }
chat_settings-set-topic-id-chat-is_-not_-a-topic-type = chat_settings-set-topic-id-chat-is_-not_-a-topic-type
chat_settings-set-topic-id-window-text = chat_settings-set-topic-id-window-text{ $stored_topic_id }
chat_settings-set-topic-id-success = chat_settings-set-topic-id-success{ $topic_id }
chat_settings-set-topic-id-topic-closed = chat_settings-set-topic-id-topic-closed{ $mention }
chat_settings-reset-topic-id-success = chat_settings-reset-topic-id-success
chat_settings-farewell-set-type-window-text = chat_settings-farewell-set-type-window-text
chat_settings-farewell-set-type-text = chat_settings-farewell-set-type-text{ $farewell_type }
chat_settings-set-type-text-button = chat_settings-set-type-text-button
chat_settings-reset-button = chat_settings-reset-button
chat_settings-set-media-button = chat_settings-set-media-button
chat_settings-set-topic-button = chat_settings-set-topic-button
chat_settings-reset-all-button = chat_settings-reset-all-button
chat_settings-set-type-photo-button = chat_settings-set-type-photo-button
chat_settings-set-type-video-button = chat_settings-set-type-video-button
chat_settings-set-type-gif-button = chat_settings-set-type-gif-button
chat_settings-set-type-sticker-button = chat_settings-set-type-sticker-button
chat_settings-set-farewell-window-text = chat_settings-set-farewell-window-text
chat_settings-greeting-set-media-window-text = chat_settings-greeting-set-media-window-text
chat_settings-greeting-set-text-window-text = chat_settings-greeting-set-text-window-text
chat_settings-greeting-set-type-window-text = chat_settings-greeting-set-type-window-text
chat_settings-greeting-set-type-text = chat_settings-greeting-set-type-text{ $greeting_type }
chat_settings-set-greeting-window-text = chat_settings-set-greeting-window-text
chat_settings-reset-reports-special-chat = chat_settings-reset-reports-special-chat
