report-reason-required = report-reason-required
report-reason-too-long = report-reason-too-long
report-bot-needs-admin-rights = report-bot-needs-admin-rights
report-reply-required = report-reply-required
reports-disabled-in_-chat = reports-disabled-in_-chat
special-chat-not_-set = special-chat-not_-set
failed-to-copy-report-message-to-special-chat = failed-to-copy-report-message-to-special-chat
special-report-message-text = special-report-message-text{ $chat_id }{ $chat_title }{ $reporter_id }{ $reporter_mention }{ $reported_id }{ $reported_mention }{ $violation_message }{ $reason }
report-message-text = report-message-text{ $reporter_id }{ $reporter_mention }{ $reported_id }{ $reported_mention }{ $violation_message }{ $reason }
report-cannot-report-selfbot = report-cannot-report-selfbot
special-report-reported_successfully = special-report-reported_successfully
special-report-message-button = special-report-message-button
