star_payments-terms-disagree = terms-disagree
star_payments-enter_kuscoin_amount = star_payments-enter_kuscoin_amount
star_payments-terms-agree = terms-agree
star_payments-invalid_amount = star_payments-invalid_amount
star_payments-amount_greater_than_zero = star_payments-amount_greater_than_zero
star_payments-amount_too_high = star_payments-amount_too_high{ $max_kuscoins_amount }{ $max_telegram_stars_amount }
star_payments-terms_agreement = star_payments-terms_agreement{ $kuscoin_amount }{ $telegram_star_amount }{ $terms_url }
star_payments-accepted_terms = star_payments-accepted_terms{ $gender }{ $terms_url }{ $time }{ $user_mention }
star_payments-buy_kuscoin_title = star_payments-buy_kuscoin_title{ $kuscoin_amount }
star_payments-buy_kuscoin_description = star_payments-buy_kuscoin_description{ $kuscoin_amount }{ $telegram_star_amount }
star_payments-error_while_sending_invoice = star_payments-error_while_sending_invoice
star_payments-declined_terms = star_payments-declined_terms{ $gender }{ $terms_url }{ $time }{ $user_mention }
refund-enter_transaction_id = refund-enter_transaction_id
refund-payment_already_refunded = refund-payment_already_refunded
refund-payment_not_paid = refund-payment_not_paid
refund-refund_period_exceeded = refund-refund_period_exceeded{ $days }
refund-not_enough_kuscoin_to_refund = refund-not_enough_kuscoin_to_refund
refund-error_while_refunding_payment = refund-error_while_refunding_payment
refund-payment_refunded = refund-payment_refunded{ $kuscoin_amount }{ $telegram_star_amount }{ $transaction_id }
refund-payment_with_tid_not_found = refund-payment_with_tid_not_found{ $transaction_id }
star_payments-payment_already_paid = star_payments-payment_already_paid
star_payments-payment_not_found = star_payments-payment_not_found
star_payments-successful_payment = star_payments-successful_payment
star_payments-closed = star_payments-closed
star_payments-goto_private_chat = star_payments-goto_private_chat
star_payments-only_in_private_chat = star_payments-only_in_private_chat
refund-only_in_private_chat = refund-only_in_private_chat
refund-goto_private_chat = refund-goto_private_chat
