predator-in-phantom-mode = predator-in-phantom-mode{ $predator_gender }
victim-in-phantom-mode = victim-in-phantom-mode{ $victim }{ $victim_gender }
victim-already-kus-ed = victim-already-kus-ed{ $victim }{ $victim_gender }
predator_zero_kukus_quantity = predator_zero_kukus_quantity
predator-has-disarm-status = predator-has-disarm-status{ $predator }{ $predator_gender }
victim-not-in-game = victim-not-in-game{ $victim }{ $victim_gender }
admin-cant-be-kused = admin-cant-be-kused
admin-self-kukus = admin-self-kukus{ $predator }{ $predator_gender }
member-self-kukus = member-self-kukus{ $predator }{ $predator_gender }
admin-kukus-protected-victim = admin-kukus-protected-victim{ $predator }{ $predator_gender }{ $victim }
admin-kukus-admin = admin-kukus-admin{ $predator }{ $predator_gender }{ $victim }{ $victim_gender }
admin-kukus-member = admin-kukus-member{ $predator }{ $predator_gender }{ $victim }
member-kukus-admin = member-kukus-admin{ $predator }{ $predator_gender }{ $victim }{ $victim_gender }
member-kukus-member = member-kukus-member{ $predator }{ $predator_gender }{ $victim }
predator_zero_kus_quantity = predator_zero_kus_quantity
admin-self-kus = admin-self-kus{ $predator }{ $predator_gender }
member-self-kus = member-self-kus{ $predator }{ $predator_gender }
admin-kus-protected-victim = admin-kus-protected-victim{ $predator }{ $predator_gender }{ $victim }
admin-break-armor-and-kus-admin = admin-break-armor-and-kus-admin{ $predator }{ $predator_gender }{ $victim }{ $victim_gender }
admin-break-armor-and-kus-member = admin-break-armor-and-kus-member{ $predator }{ $predator_gender }{ $victim }
admin-dont-break-armor-and-get-disarm = admin-dont-break-armor-and-get-disarm{ $predator }{ $predator_gender }{ $victim }{ $victim_gender }
admin-kus-admin = admin-kus-admin{ $predator }{ $predator_gender }{ $victim }{ $victim_gender }
admin-kus-member = admin-kus-member{ $predator }{ $predator_gender }{ $victim }
member-break-armor-and-kus-admin = member-break-armor-and-kus-admin{ $predator }{ $predator_gender }{ $victim }{ $victim_gender }
member-break-armor-and-kus-member = member-break-armor-and-kus-member{ $predator }{ $predator_gender }{ $victim }
member-dont-break-armor-and-get-restrict = member-dont-break-armor-and-get-restrict{ $predator }{ $predator_gender }{ $victim }{ $victim_gender }
member-kus-admin = member-kus-admin{ $predator }{ $predator_gender }{ $victim }{ $victim_gender }
member-kus-member = member-kus-member{ $predator }{ $victim }{ $predator_gender }
