settings--settings = settings--settings
settings--settings-text = settings--settings-text { $language } { $gender }
settings--closed = settings--closed
settings--gender-male = settings--gender-male
settings--gender-female = settings--gender-female
settings--gender-text = settings--gender-text
settings--gender-selected-text = settings--gender-selected-text { $gender }
settings--gender-button = settings--gender-button
settings--language = settings--language
settings--lang = settings--lang
settings--choose_language = settings--choose_language
settings--language-selected-text = settings--language-selected-text { $language }
settings--language-code = settings--language-code { $language_code }
