item-kus-name = Кусь
item-kus-description = Кусь — укуси свою жертву и заставь еë молчать на минуту!
item-armor-name = Щит
item-armor-description = Щит — с некоторым шансом защитит тебя от укуса.
item-kukus-name = Кукусь
item-kukus-description = Кукусь - усиленная версия обычного Кусь. Даëт возможность укусить жертву и заставить молчать еë 5 минут!
item-kuscoin-name = КусьКоїн
item-kuscoin-description = КусьКоин — валюта, которую можно потратить на покупку разных предметов.
item-vip-name = VIP
item-vip-description = item-vip-description
