kus_proc-kus--predator_kus_quantity_zero = kus_proc-kus--predator_kus_quantity_zero
kus_proc-kus--victim_restricted = kus_proc-kus--victim_restricted { $victim }
kus_proc-kus--admin_bite_admin = kus_proc-kus--admin_bite_admin { $predator } { $victim }
kus_proc-kus--member_bite_admin = kus_proc-kus--member_bite_admin { $predator } { $victim }
kus_proc-kus--admin_bite_protected_member = kus_proc-kus--admin_bite_protected_member { $predator } { $victim }
kus_proc-kus--admin_break_armor = kus_proc-kus--admin_break_armor { $predator } { $victim }
kus_proc-kus--member_break_armor = kus_proc-kus--member_break_armor { $predator } { $victim }
kus_proc-kus--member_bite_armor = kus_proc-kus--member_bite_armor { $predator } { $victim }
kus_proc-kus--member_bite_member = kus_proc-kus--member_bite_member { $predator } { $victim }
