restrictions--ban-usage = restrictions--ban-usage
restrictions--set-user-or-reply = restrictions--set-user-or-reply
restrictions--cant-ban-admin = restrictions--cant-ban-admin
restrictions--cant-ban-self = restrictions--cant-ban-self
restrictions--ban-error = restrictions--ban-error
restrictions--forever = restrictions--forever
restrictions--ban-text = restrictions--ban-text { $admin_mention } { $until_date } { $victim_mention } { $reason }
restrictions--ban-sender-chat-error = restrictions--ban-sender-chat-error
restrictions--ban-sender-chat = restrictions--ban-sender-chat
restrictions--kick-usage = restrictions--kick-usage
restrictions--cant-kick-admin = restrictions--cant-kick-admin
restrictions--cant-kick-self = restrictions--cant-kick-self
restrictions--kick-error = restrictions--kick-error
restrictions--kick-text = restrictions--kick-text { $admin_mention } { $victim_mention } { $reason }
restrictions--sender-chat-not-implemented = restrictions--sender-chat-not-implemented
restrictions--mute-usage = restrictions--mute-usage
restrictions--cant-mute-admin = restrictions--cant-mute-admin
restrictions--cant-mute-self = restrictions--cant-mute-self
restrictions--mute-error = restrictions--mute-error
restrictions--mute-text = restrictions--mute-text { $admin_mention } { $until_date } { $victim_mention } { $reason }
restrictions--cant-mute-sender-chat = restrictions--cant-mute-sender-chat
restrictions--pardon-usage = restrictions--pardon-usage
restrictions--cant-pardon-admin = restrictions--cant-pardon-admin
restrictions--cant-pardon-self = restrictions--cant-pardon-self
restrictions--not-enough-rights-to-pardon = restrictions--not-enough-rights-to-pardon
restrictions--pardon-error = restrictions--pardon-error
restrictions--pardon-text = restrictions--pardon-text { $admin_mention } { $victim_mention } { $reason }
restrictions--set_reason-usage = restrictions--set_reason-usage
restrictions--set_reason-not_restriction_message_or_expired = restrictions--set_reason-not_restriction_message_or_expired
restrictions--set_reason-mute_message = restrictions--set_reason-mute_message { $admin_mention } { $edited_by } { $until_date } { $victim_mention } { $reason }
restrictions--set_reason-ban_message = restrictions--set_reason-ban_message { $admin_mention } { $edited_by } { $until_date } { $victim_mention } { $reason }
restrictions--set_reason-kick_message = restrictions--set_reason-kick_message { $admin_mention } { $victim_mention } { $reason } { $edited_by }
restrictions--set_reason-pardon_message = restrictions--set_reason-pardon_message { $admin_mention } { $victim_mention } { $reason } { $edited_by }
restrictions--ban-show-advanced-info = restrictions--ban-show-advanced-info
restrictions--ban-usage-advanced = restrictions--ban-usage-advanced
restrictions--close-advanced-info = restrictions--close-advanced-info
restrictions--closed = restrictions--closed
