item-kus-name = Kus
item-kus-description = Иite your victim and make him silent for 1 minute!
item-armor-name = Armor
item-armor-description = Цith some chance it can protect you from the bite.
item-kukus-name = Kukus
item-kukus-description = Іtronger version of common Kus. Allows you to bite the victim and make them silent over 5 minutes!
item-kuscoin-name = KusCoin
item-kuscoin-description = Сurrency, can be spent for the purchase of various items.
item-vip-name = VIP
item-vip-description = item-vip-description
