item-kus-name = Kus
item-kus-description = Bite your victim and silence them for a whole minute!
item-armor-name = Armor
item-armor-description = Has a chance to protect you from a bite.
item-kukus-name = Kukus
item-kukus-description = An enhanced version of the regular Bite. Allows you to bite your victim and silence them for over 5 minutes!
item-kuscoin-name = KusCoin
item-kuscoin-description = Currency that can be spent to buy various items.
item-vip-name = VIP
item-vip-description = Special status granting access to exclusive features and items.
