inventory--inventory = inventory--inventory
inventory--i = inventory--i
inventory--items = inventory--items
inventory--resources = inventory--resources
inventory--weapons = inventory--weapons
inventory--prev-page = inventory--prev-page
inventory--next-page = inventory--next-page
inventory--close = inventory--close
inventory--items-text = inventory--items-text { $items }
inventory--not-implemented = inventory--not-implemented
inventory--closed = inventory--closed
inventory--unknown-window = inventory--unknown-window
inventory--resources-text = inventory--resources-text { $resources }
inventory--weapons-not-implemented = inventory--weapons-not-implemented
