keyboards--main-button = 📜 Основные
keyboards--admin-button = 👮‍♂️ Админ
keyboards--vip-button = 👑 VIP
keyboards--other-button = 🔮 Другие
keyboards--profile-button = 👤 Профиль
keyboards--language-button = 🌐 Язык | Language
keyboards--commands-button = 📚 Команды
keyboards--add_to_group-button = 🚀 Добавить Бота в группу
keyboards--inventory-button = 📦 Инвентарь
keyboards--settings-button = ⚙️ Настройки
keyboards--close-button = ❌ Закрыть
