language--language = language--language
language--lang = language--lang
language--choose_lang = language--choose_lang
language--select_callback-success = language--select_callback-success { $language }
language--en = 🇺🇸 English
language--uk = 🇺🇦 Українська
language--ru = 🇷🇺 Российский
language--pl = 🇵🇱 Polski
language--de = 🇩🇪 Deutsch
language--ja = 🇯🇵 日本語
