language--language = язык
language--lang = язык
language--choose_lang = 🌐 Выберите язык
language--select_callback-success = Выбран язык: { $language }
language--en = 🇺🇸 English
language--uk = 🇺🇦 Українська
language--ru = 🇷🇺 Российский
language--pl = 🇵🇱 Polski
language--de = 🇩🇪 Deutsch
language--ja = 🇯🇵 日本語
