restrictions--ban-usage = restrictions--ban-usage
restrictions--set-user-or-reply = restrictions--set-user-or-reply
restrictions--cant-ban-admin = restrictions--cant-ban-admin
restrictions--cant-ban-self = restrictions--cant-ban-self
restrictions--ban-error = restrictions--ban-error
restrictions--ban = restrictions--ban { $admin_mention } { $string_time } { $victim_mention } { $reason }
restrictions--ban-sender-chat-error = restrictions--ban-sender-chat-error
restrictions--ban-sender-chat = restrictions--ban-sender-chat
restrictions--kick-usage = restrictions--kick-usage
restrictions--cant-kick-admin = restrictions--cant-kick-admin
restrictions--cant-kick-self = restrictions--cant-kick-self
restrictions--kick-error = restrictions--kick-error
restrictions--kick = restrictions--kick { $admin_mention } { $victim_mention } { $reason }
restrictions--sender-chat-not-implemented = restrictions--sender-chat-not-implemented
restrictions--mute-usage = restrictions--mute-usage
restrictions--cant-mute-admin = restrictions--cant-mute-admin
restrictions--cant-mute-self = restrictions--cant-mute-self
restrictions--mute-error = restrictions--mute-error
restrictions--mute = restrictions--mute { $admin_mention } { $string_time } { $victim_mention } { $reason }
restrictions--cant-mute-sender-chat = restrictions--cant-mute-sender-chat
restrictions--pardon-usage = restrictions--pardon-usage
restrictions--cant-pardon-admin = restrictions--cant-pardon-admin
restrictions--cant-pardon-self = restrictions--cant-pardon-self
restrictions--not-enough-rights-to-pardon = restrictions--not-enough-rights-to-pardon
restrictions--pardon-error = restrictions--pardon-error
restrictions--pardon = restrictions--pardon { $admin_mention } { $victim_mention } { $reason }
restrictions--forever = restrictions--forever
