shop-choose_item_to_buy_text = shop-choose_item_to_buy_text
shop-unknown_item_type = shop-unknown_item_type
shop-closed = shop-closed
shop-purchase_failed = shop-purchase_failed
shop-purchase_successful = shop-purchase_successful{ $name }{ $emoji }{ $actual_amount }{ $total_cost }
shop-close = shop-close
shop-cancelled = shop-cancelled
shop-ask_item_amount = shop-ask_item_amount{ $name }{ $emoji }{ $description }{ $kus_coin_price }{ $amount_per_price }
shop-only_in_private_chat = shop-only_in_private_chat
shop-confirm_item_purchase = shop-confirm_item_purchase{ $name }{ $emoji }{ $actual_amount }{ $total_cost }
shop-confirm = shop-confirm
shop-back_to_shop = shop-back_to_shop
shop-goto_private_chat = shop-goto_private_chat
shop-not_enough_kuscoin = shop-not_enough_kuscoin
