terms-disagree = terms-disagree
star_payments-enter_kuscoin_amount = star_payments-enter_kuscoin_amount
terms-agree = terms-agree
star_payments-invalid_amount = star_payments-invalid_amount
star_payments-amount_greater_than_zero = star_payments-amount_greater_than_zero
star_payments-amount_too_high = star_payments-amount_too_high{ $max_kuscoins_amount }{ $max_telegram_stars_amount }
star_payments-terms_agreement = star_payments-terms_agreement{ $kuscoin_amount }{ $telegram_star_amount }{ $terms_url }
star_payments-accepted_terms = star_payments-accepted_terms{ $gender }{ $terms_url }{ $time }{ $user_mention }
star_payments-buy_kuscoin_title = star_payments-buy_kuscoin_title{ $kuscoin_amount }
star_payments-buy_kuscoin_description = star_payments-buy_kuscoin_description{ $kuscoin_amount }{ $telegram_star_amount }
star_payments-error_while_sending_invoice = star_payments-error_while_sending_invoice
star_payments-declined_terms = star_payments-declined_terms{ $gender }{ $terms_url }{ $time }{ $user_mention }
star_payments-enter_transaction_id = star_payments-enter_transaction_id
star_payments-payment_already_refunded = star_payments-payment_already_refunded
star_payments-payment_not_paid = star_payments-payment_not_paid
star_payments-refund_period_exceeded = star_payments-refund_period_exceeded{ $days }
star_payments-not_enough_kuscoin_to_refund = star_payments-not_enough_kuscoin_to_refund
star_payments-error_while_refunding_payment = star_payments-error_while_refunding_payment
star_payments-payment_refunded = star_payments-payment_refunded{ $kuscoin_amount }{ $telegram_star_amount }{ $transaction_id }
star_payments-payment_with_tid_not_found = star_payments-payment_with_tid_not_found{ $transaction_id }
star_payments-payment_already_paid = star_payments-payment_already_paid
star_payments-payment_not_found = star_payments-payment_not_found
star_payments-successful_payment = star_payments-successful_payment
